### PR TITLE
#164516500 Enable social login via google

### PR DESCRIPTION
**Pull request by Paccy10**
**What does this PR do?**

Enable social login Via Google

**Description of Task to be completed?**

This PR enables the user of the application to log in using his/her Google account credentials

**How should this be manually tested?**

- Go to postman type [http://localhost:3000/api/users/login/google](http://localhost:3000/api/users/login/google)

- Then add the access token in the body and send

- Then you will get a response that contains a token and some of your info

**What are the relevant pivotal tracker stories?**

[#164516500](https://www.pivotaltracker.com/n/projects/2316906)

**Screenshots (if appropriate)**

The response should like this one:

Screen Shot 2019-04-04 at 14 21 56

### CODE REVIEW

**Comment by blaisebakundukize** [comment]
Hello @Paccy10, thank you for the good work you did. Unfortunately, there are still some changes to make. Firstly, There are 3 violations found by Hound. I think it would be better if you take your time to resolve it. Secondly, Travis is still failing. Thirdly, you have two issues to fix for the codeclimate to rate great your work. I released that there are similar blocks found. To check that you can click this link [Code Climate issue](https://codeclimate.com/github/andela/bad_ass-ah-backend/pull/17). Lastly, you have three comments, I think it'd be better if you squash some and remain with one. Thanks

**Comment by Jaman-dedy** [comment]
Please @Paccy10 Squash your commits

**Comment by itsgratien** [comment]
@Paccy10  great job, but in your passport middleware for google there is something you need to change, replace console.log to return error in json format, another things i think you can change, on google passport, you need to disable session because we no longer need session, the only things we need is to generate token.

**Comment by blaisebakundukize** [comment]
Hello @Paccy10 , I like the way you handled this feature. But I have a problem with creating a new user using google account. I realize that you put user displayName from google in username field in the database. This field should be unique and sometimes different people might have a similar name. The problem is if someone register using google account and there is a similar username, it'll fail. I think you can use user id from google or use other unique property like email again. Thanks! Good work

**Pull request merged**
