### PR TITLE
#164489923 Setting JWT Token

### PR DESCRIPTION
**Pull request by itsgratien**
#### What does this PR do?
Creating JWT(jsonwebtoken) token.

#### Description of Task to be completed?
this PR used to set token based authentication using [jsonwebtoken](https://www.npmjs.com/package/jsonwebtoken).
when user create account, he/she should receive token.

This PR also have the following endpoints working.

- POST /api/users

#### How should this be manually tested ?
- open API Testing tools (Postman)
- in postman url write [http://localhost:3000/api/users](http://localhost:3000/api/users)
- create user with username,password and email and run
- You will receive created user with token.

#### Screenshots
image

#### What are the relevant pivotal tracker stories?**
[#164489923](https://www.pivotaltracker.com/n/projects/2316906/stories/164489923)

### CODE REVIEW

**Review by Paccy10 — COMMENTED** [review]
Good job @itsgracian , but I think it would be better if you remain with 1 commit in your PR and also make its message very descriptive.

**Comment by Jaman-dedy** [comment]
Good Job Gratien, I see now travis is well configured, but it could be better to remove the config.json from your config folder, since it's not doing any thing there because config.js does all the work... thanks

**Review by Jaman-dedy — APPROVED** [review]

**Review by Paccy10 — COMMENTED** [review]
@itsgracian the commit message is not following the engineering playbook conventions

**Comment by itsgratien** [comment]
@Jaman-dedy  done

**Comment by blaisebakundukize** [comment]
Got job @itsgracian, I appreciate the way you handled this but I think it'd be better if you add other necessary fields in the PR description(template). 
For example:
#### How should this be manually tested?
And about the commit message, just follow the andela convention for commit message.

**Comment by itsgratien** [comment]
@Paccy10 ooh thank you to remind,let me change it

**Comment by ruganda** [comment]
Good work @itsgracian, Please include how this can be manually tested in the PR description.

**Comment by ruganda** [comment]
@itsgracian  You have failing checks on your Pr, Please fix them

**Comment by itsgratien** [comment]
@blaisebakundukize done.

**Pull request merged**
