### PR TITLE
#164489920 added test environment

### PR DESCRIPTION
**Pull request by cop1fab**
#### What does this PR do?
This PR sets unit testing; ensuring all implemented functionality is tested henceforth.  This ensures the back end has all functionality working as intended. 
#### Description of Task to be completed?
- configure the test environment to use mocha and chai 
#### How should it be tested manually?
After cloning the repo, run 
npm install to install all necessary dependencies then run npm run test 
#### Pivotal Tracker story?
[#164489920](https://www.pivotaltracker.com/story/show/164489920)

### CODE REVIEW

**Review by Jaman-dedy — APPROVED** [review]

**Review by Paccy10 — COMMENTED** [review]
I think in the user test we have to use es6

**Comment by cop1fab** [comment]
That is true, I wrote it using ES5 because we do not have babel set up yet.

**Review by Paccy10 — COMMENTED** [review]
I think you can set it up

**Comment by blaisebakundukize** [comment]
I appreciate the way you configured mocha and test script, but I see that you have used es5. I think you'd have installed the needed packages to transpile es6 to es5, then use es6. The test script, I see that it run all file inside the test folder. I was wondering if we could specify the exact files. For example, I want the script to run files have ```.test.js``` extension.

**Comment by Jaman-dedy** [comment]
Hello @cop1fab , I think that it can be better to have one commit per PR, thanks to set it

**Comment by ruganda** [comment]
@cop1fab, Good work. Please look into;
- using es6,
- changing your PR title to follow our conventions,
- editing your Pr description to follow the conventions as well.

**Comment by cop1fab** [comment]
> @cop1fab, Good work. Please look into;
> 
> * using es6,
> * changing your PR title to follow our conventions,
> * editing your Pr description to follow the conventions as well.

Thank you for the feedback, this is has been added to my priority list.

**Review by itsgratien — APPROVED** [review]

**Comment by blaisebakundukize** [comment]
Thank you Copain, for the PR, I appreciate the work you did and the effort you put in. But I see a lot of comments of HoundCI about the code style. Somewhere it comments that you missed semicolon and arrow-space. Just configure well eslint in your editor so that next time you'll take care of the code style.

**Review by blaisebakundukize — APPROVED** [review]

**Review by Jaman-dedy — APPROVED** [review]

**Review by ruganda — APPROVED** [review]

**Pull request merged**
